config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :articles do #Los comentarios son un recurso de los articulos
  	resources :comments, only: [:create, :destroy, :update]#Ya no se podrá acceder a /comments directo, sino /articles/:id/comments
  end
  devise_for :users

  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	validates :title, presence: true, uniqueness: true #Valida que no esté vacio, y no esté repetido
	validates :body, presence: true, length: {minimum: 10} #Valida tamaño minimo
	has_many :comments #Asociacion con comentarios
	before_create :initialize_visits_count
	after_create :save_categories
	
	has_attached_file :cover, styles: { medium: "1280*720", thumb:"800*600"}
	#Requerido por paperclip :cover es el "nombre" del adjunto
	# Validate content type
  	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/

  	def update_visits_count
			self.update(visits_count: self.visits_count + 1)
	end

	def categories=(value) #Custom setter
		@categories = value
	end

  	private
		def initialize_visits_count
			self.visits_count = 0
		end

		def save_categories
			@categories.each do |category_id|
				HasCategory.create(category_id: category_id, article_id: self.id)
			end
		end
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/has_category.rb
class HasCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :articles
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_categories

  private
  	def set_categories
  		@categories = Category.all
  	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index] #Helper de devise para pedir autenticacion antes de ejecutas acciones
  before_action :set_article, except: [:index, :new, :create] #Codigo mas limpio buscando el articulo con callback

  def index
  	@articles = Article.all
  end

  def show
    @article.update_visits_count
    @comment = Comment.new #Necesario para comentarios en articulo
  end

  #Crea un articulo en blanco para enviarlo al formulario
  def new
  	@article = Article.new
    @categories = Category.all
  end


  def create
  	@article = current_user.articles.new(article_params)
    @article.categories = params[:categories]
   	if @article.save
   		redirect_to @article
   	else
   		render :new
   	end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  def edit
    
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :cover, :categories)
    end

    def set_article
      @article = Article.find(params[:id])
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :color)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_article
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.article = @article

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end

    def set_article
      @article = Article.find(params[:article_id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
	<h1><%=accion%> un articulo</h1>

	<%= form_for(@article) do |f| %>

	<!--Muesta los errores ocurridos al intentar guardar articulo -->
	<% @article.errors.full_messages.each do |message|%>
		<div class="error top-space">
			* <%= message %>
		</div>
	<%end%>

		<div class="field">
			<%= f.text_field :title, placeholder: "El mejor cuento de todos...", class:"form-control"%>
		</div>
		<div class="field">
			Portada: <%= f.file_field :cover %>
		</div>
		<div class="field">
			<%= f.text_area :body, placeholder: "Erase una vez...", style:" height:300px; font-family:'Roboto';	", class:"form-control "%>
		</div>
		<div class="field">
		<label>Categorias: </label>
			<% @categories.each do |category|%>
				<div class="field">
					<%= check_box_tag "categories[]", category.id %> <%= category.name%>
				</div>
			<%end%>
		</div>
		<div class="field">
			<%= f.submit "Guardar", class:"btn be-blue white"%>
		</div>
	<%end%>

app/views/articles/edit.html.erb
<div style="width: 80%;margin: 0 auto;">
	<%= render 'form', accion: "Editar"%>
</div>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
	<h1><%= link_to article.title, article %></h1>
	<div>
		<%= article.body %> - <%= link_to "Eliminar", article, method: :delete %>
	</div>
<%end%>

app/views/articles/new.html.erb
<div style="width: 80%;margin: 0 auto;">
	<%= render 'form', accion: "Escribir"%>
</div>

app/views/articles/show.html.erb
<h1><%=@article.title%></h1>
<p>
	Visitas: <%= @article.visits_count %>
</p>
<div class="field">
	<%= image_tag @article.cover.url() %>
</div>
<div>
	<%= @article.body%>
</div>
<div class="top-space top-padding top-marging">
	<%= link_to "Editar", edit_article_path(@article) %>
</div>
<div class="field">
	<h3>Comentarios</h3>
	<%= render 'comments/form' %>
	<ul>
		<% @article.comments.each do |comment|%>
		<li>
			<%=comment.body%> - <%= comment.user.email%>
		</li>
		<%end%>
	</ul>
</div>

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.color_field :color %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.color %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @category.color %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/comments/_form.html.erb
<%= form_for([@article,@comment], remote: true) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<!--<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Article</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.article %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>
-->
<!-- LOS COMENTARIOS AHORA SE HARÁN DESDE EL ARTICULO, NO SERÁ NECESARIO ESTA VISTA, A DEMAS DE GENERAR ERROR. -->

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet"> 
  </head>

  <body>
  	<%= render "partials/navigation" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/partials/_navigation.html.erb
<header>
 <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet"> 
  	<nav class="be-blue white large-padding bold-font">
  		<ul style="list-style-type: none" class="no-list row center-xs middle-xs">
  			<li class="col-xs ">
  			<h1 class="no-marging no-padding" id="logo"><%= link_to "BLOG ON RAILS", root_path %></h1>
  			</li>
	  		<li class="col-xs bold-font">
	  			<%= link_to "Articulos", articles_path, class:"bold-font", style:"font-family:'Roboto', sans-serif"%>
	  		</li>

        <% @categories.each do |category|%>
          <li class="col-xs">
            <%= link_to category.name, category%>
          </li>
        <% end %>

        </li>
        <% if user_signed_in? %>
          <li class="col-xs">
          <%= link_to "Nuevo articulo", new_article_path%>
        </li>
        <li class="col-xs">
          <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete%>
        </li>
        <%else%>
          <li class="col-xs">
          <%= link_to "Iniciar sesión", new_user_session_path%>
          </li>
          <li class="col-xs">
          <%= link_to "Registro", new_user_registration_path%>
          </li>
        <%end%>
  		</ul>
  	</nav>
  </header>

app/views/welcome/index.html.erb
<%if user_signed_in?%>
	<h1>Bienvenido <%= current_user.email %></h1>
<%else%>
	<h1>Bienvenido!</h1>
<%end%>